from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List
from datetime import datetime
import database, models, schemas, auth

router = APIRouter(
    prefix="/teacher",
    tags=["teacher"],
    responses={404: {"description": "Not found"}},
)

def get_current_teacher(current_user: models.User = Depends(auth.get_current_active_user)):
    if current_user.role not in [models.UserRole.TEACHER, models.UserRole.SCHOOL_ADMIN, models.UserRole.SUPER_ADMIN]:
         raise HTTPException(status_code=403, detail="Not enough permissions")
    return current_user


@router.post("/students/", response_model=schemas.Student)
def create_student(student: schemas.StudentCreate, db: Session = Depends(database.get_db), current_user: models.User = Depends(get_current_teacher)):
    # Verify grade exists and belongs to the same school
    grade = db.query(models.Grade).filter(
        models.Grade.id == student.grade_id,
        models.Grade.school_id == current_user.school_id
    ).first()
    if not grade:
        raise HTTPException(status_code=404, detail="Grade not found in this school")
    
    # If class_id is provided, verify it
    if student.class_id:
        class_obj = db.query(models.Class).filter(
            models.Class.id == student.class_id,
            models.Class.school_id == current_user.school_id
        ).first()
        if not class_obj:
            raise HTTPException(status_code=404, detail="Class not found in this school")
        if class_obj.grade_id != student.grade_id:
            raise HTTPException(status_code=400, detail="Class does not belong to the selected grade")

    new_student = models.Student(
        name=student.name,
        grade_id=student.grade_id,
        class_id=student.class_id,
        school_id=current_user.school_id,
        active=True
    )
    db.add(new_student)
    db.commit()
    db.refresh(new_student)
    return new_student

@router.get("/students/", response_model=List[schemas.Student])
def read_students(db: Session = Depends(database.get_db), current_user: models.User = Depends(get_current_teacher)):
    return db.query(models.Student).filter(models.Student.school_id == current_user.school_id).all()

@router.post("/assignments/", response_model=schemas.Assignment)
def create_assignment(assignment: schemas.AssignmentCreate, db: Session = Depends(database.get_db), current_user: models.User = Depends(get_current_teacher)):
    # Verify class belongs to school
    class_obj = db.query(models.Class).filter(
        models.Class.id == assignment.assigned_to_class_id,
        models.Class.school_id == current_user.school_id
    ).first()
    if not class_obj:
        raise HTTPException(status_code=404, detail="Class not found")
        
    new_assignment = models.Assignment(
        title=assignment.title,
        description=assignment.description,
        due_date=assignment.due_date,
        status=assignment.status,
        teacher_id=current_user.id,
        class_id=assignment.assigned_to_class_id,
        subject_id=assignment.subject_id
    )
    db.add(new_assignment)
    db.commit()
    db.refresh(new_assignment)
    return new_assignment

@router.get("/assignments/", response_model=List[schemas.Assignment])
def read_assignments(db: Session = Depends(database.get_db), current_user: models.User = Depends(get_current_teacher)):
    return db.query(models.Assignment).filter(models.Assignment.teacher_id == current_user.id).all()

@router.post("/assignments/ai-generate", response_model=schemas.Assignment)
def generate_ai_assignment(topic: str, grade_level: str, difficulty: str, question_count: int, db: Session = Depends(database.get_db), current_user: models.User = Depends(get_current_teacher)):
    # Mock AI Generation
    mock_title = f"AI Generated Quiz: {topic}"
    mock_description = f"A {difficulty} level quiz with {question_count} questions about {topic} for {grade_level}. Generated by AI."
    
    new_assignment = models.Assignment(
        title=mock_title,
        description=mock_description,
        status=models.AssignmentStatus.DRAFT,
        teacher_id=current_user.id,
        due_date=datetime.now() # temp
    )
    db.add(new_assignment)
    db.commit()
    db.refresh(new_assignment)
    return new_assignment

@router.get("/classes/", response_model=List[schemas.Class])
def read_classes(db: Session = Depends(database.get_db), current_user: models.User = Depends(get_current_teacher)):
    return db.query(models.Class).filter(models.Class.school_id == current_user.school_id).all()

@router.get("/subjects/", response_model=List[schemas.Subject])
def read_subjects(db: Session = Depends(database.get_db), current_user: models.User = Depends(get_current_teacher)):
    return db.query(models.Subject).filter(models.Subject.school_id == current_user.school_id).all()

@router.get("/grades/", response_model=List[schemas.Grade])
def read_grades(db: Session = Depends(database.get_db), current_user: models.User = Depends(get_current_teacher)):
    return db.query(models.Grade).filter(models.Grade.school_id == current_user.school_id).all()
