# publish.ps1
# ONE-COMMAND deploy to http://35.226.218.109:8000
$ErrorActionPreference = "Stop"

$PROJECT_ID  = "project-7b2578b2-0b43-448e-80c"
$VM_NAME     = "learnmist-server"
$ZONE        = "us-central1-a"
$PACK        = "deploy_pack.tar.gz"
$SERVER_IP   = "35.226.218.109"
$SERVER_PORT = "8000"

function Step([string]$n, [string]$msg) {
    Write-Host ""
    Write-Host "[$n] $msg" -ForegroundColor Cyan
}

function OK([string]$msg) {
    Write-Host "    OK: $msg" -ForegroundColor Green
}

function Fail([string]$msg) {
    Write-Host "    FAIL: $msg" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "================================================" -ForegroundColor Yellow
Write-Host "  BrinymistSchool  ->  http://${SERVER_IP}:${SERVER_PORT}" -ForegroundColor Yellow
Write-Host "================================================" -ForegroundColor Yellow

Step "1/6" "Setting GCP project..."
gcloud config set project $PROJECT_ID | Out-Null
if ($LASTEXITCODE -ne 0) { Fail "gcloud config set project failed" }
OK "Project: $PROJECT_ID"

Step "2/6" "Writing frontend/.env.production.local..."
$envLines = @(
    "# AUTO-GENERATED by publish.ps1",
    "VITE_API_URL=/",
    "VITE_WS_URL=ws://${SERVER_IP}:${SERVER_PORT}"
)
$envLines | Set-Content -Path "frontend\.env.production.local" -Encoding UTF8
OK "frontend/.env.production.local written"

Step "3/6" "Building frontend..."
if (Test-Path "frontend\dist") { Remove-Item "frontend\dist" -Recurse -Force }
Push-Location frontend
npm install --silent
if ($LASTEXITCODE -ne 0) { Pop-Location; Fail "npm install failed" }
npm run build
if ($LASTEXITCODE -ne 0) { Pop-Location; Fail "Frontend build failed" }
Pop-Location
OK "Build verified"

Step "4/6" "Packaging backend + frontend/dist..."
if (Test-Path $PACK) { Remove-Item $PACK -Force }
tar.exe -czf $PACK --exclude="backend/venv" --exclude="backend/__pycache__" --exclude="backend/*.pyc" --exclude="backend/*.db" backend frontend/dist
if ($LASTEXITCODE -ne 0) { Fail "tar failed" }
$sizeMB = [math]::Round((Get-Item $PACK).Length / 1MB, 1)
OK "Package: $PACK ($sizeMB MB)"

Step "5/6" "Uploading to VM ${VM_NAME}..."
gcloud compute scp $PACK "deploy_remote.sh" "${VM_NAME}:/home/balav/" --zone=$ZONE --project=$PROJECT_ID
if ($LASTEXITCODE -ne 0) { Fail "Upload failed" }
OK "Upload complete"

Step "6/6" "Running remote deployment..."
gcloud compute ssh $VM_NAME --zone=$ZONE --project=$PROJECT_ID --command="sed -i 's/\r$//' ~/deploy_remote.sh && chmod +x ~/deploy_remote.sh && bash ~/deploy_remote.sh"
if ($LASTEXITCODE -ne 0) { Fail "Remote deployment failed" }

Write-Host ""
Write-Host "================================================" -ForegroundColor Green
Write-Host "  Deployment Complete!" -ForegroundColor Green
Write-Host "  App:      http://${SERVER_IP}:${SERVER_PORT}/login" -ForegroundColor Yellow
Write-Host "================================================" -ForegroundColor Green
