# publish.ps1
# ONE-COMMAND deploy to http://34.173.65.197:8000
# Usage: powershell -ExecutionPolicy Bypass -File publish.ps1
#
# Steps:
#   1. Sets GCP project
#   2. Writes frontend/.env.production.local (VITE_API_URL=/) — highest priority for Vite
#   3. Cleans + builds frontend, verifies no api.learnmist.com in output
#   4. Packages backend + frontend/dist
#   5. Uploads to GCP VM (learnmist-server, us-central1-a)
#   6. Runs remote script: stops Docker web, keeps Postgres, force-replaces files, restarts uvicorn
#   7. Health check prints the live bundle name served

$ErrorActionPreference = "Stop"

$PROJECT_ID  = "project-7b2578b2-0b43-448e-80c"
$VM_NAME     = "learnmist-server"
$ZONE        = "us-central1-a"
$PACK        = "deploy_pack.tar.gz"
$SERVER_IP   = "34.173.65.197"
$SERVER_PORT = "8000"

function Step([string]$n, [string]$msg) {
    Write-Host ""
    Write-Host "[$n] $msg" -ForegroundColor Cyan
}
function OK([string]$msg)   { Write-Host "    OK: $msg" -ForegroundColor Green }
function Fail([string]$msg) { Write-Host "    FAIL: $msg" -ForegroundColor Red; exit 1 }

Write-Host ""
Write-Host "================================================" -ForegroundColor Yellow
Write-Host "  LearnmistSchool  ->  http://${SERVER_IP}:${SERVER_PORT}" -ForegroundColor Yellow
Write-Host "================================================" -ForegroundColor Yellow

# 1. Set GCP project
Step "1/6" "Setting GCP project..."
gcloud config set project $PROJECT_ID | Out-Null
if ($LASTEXITCODE -ne 0) { Fail "gcloud config set project failed" }
OK "Project: $PROJECT_ID"

# 2. Write .env.production.local — Vite loads this AFTER .env.production, so it wins
Step "2/6" "Writing frontend/.env.production.local..."
$envLines = @(
    "# AUTO-GENERATED by publish.ps1",
    "VITE_API_URL=/",
    "VITE_WS_URL=ws://${SERVER_IP}:${SERVER_PORT}"
)
$envLines | Set-Content -Path "frontend\.env.production.local" -Encoding UTF8
OK "frontend/.env.production.local written (VITE_API_URL=/)"

# 3. Clean dist, build, verify
Step "3/6" "Building frontend..."
if (Test-Path "frontend\dist") { Remove-Item "frontend\dist" -Recurse -Force }

Push-Location frontend
    npm install --silent
    if ($LASTEXITCODE -ne 0) { Pop-Location; Fail "npm install failed" }
    npm run build
    if ($LASTEXITCODE -ne 0) { Pop-Location; Fail "Frontend build failed" }
Pop-Location

$jsFiles = Get-ChildItem "frontend\dist\assets\*.js" -ErrorAction SilentlyContinue
if (-not $jsFiles) { Fail "No JS files found in frontend/dist/assets" }

$badUrl = $jsFiles | Select-String -Pattern "api\.learnmist\.com" -Quiet
if ($badUrl) { Fail "Bundle still contains 'api.learnmist.com' — check .env.production.local" }

$bundleName = ($jsFiles | Select-Object -First 1).Name
OK "Build verified: $bundleName (no api.learnmist.com)"

# 4. Package
Step "4/6" "Packaging backend + frontend/dist..."
if (Test-Path $PACK) { Remove-Item $PACK -Force }
tar.exe -czf $PACK `
    --exclude="backend/venv" `
    --exclude="backend/__pycache__" `
    --exclude="backend/*.pyc" `
    --exclude="backend/*.db" `
    backend `
    frontend/dist
if ($LASTEXITCODE -ne 0) { Fail "tar failed" }
$sizeMB = [math]::Round((Get-Item $PACK).Length / 1MB, 1)
OK "Package: $PACK ($sizeMB MB)"

# 5. Upload
Step "5/6" "Uploading to VM ${VM_NAME}..."
gcloud compute scp $PACK "deploy_remote.sh" "${VM_NAME}:/home/balav/" --zone=$ZONE --project=$PROJECT_ID
if ($LASTEXITCODE -ne 0) { Fail "Upload failed" }
OK "Upload complete"

# 6. Remote deploy
Step "6/6" "Running remote deployment..."
gcloud compute ssh $VM_NAME --zone=$ZONE --project=$PROJECT_ID `
    --command="chmod +x ~/deploy_remote.sh && bash ~/deploy_remote.sh"
if ($LASTEXITCODE -ne 0) { Fail "Remote deployment failed" }

Write-Host ""
Write-Host "================================================" -ForegroundColor Green
Write-Host "  Deployment Complete!" -ForegroundColor Green
Write-Host "  App:      http://${SERVER_IP}:${SERVER_PORT}/login" -ForegroundColor Yellow
Write-Host "  API Docs: http://${SERVER_IP}:${SERVER_PORT}/docs" -ForegroundColor Yellow
Write-Host "================================================" -ForegroundColor Green
