ALTER TABLE questions ADD COLUMN IF NOT EXISTS media_url VARCHAR(500);
ALTER TABLE questions ADD COLUMN IF NOT EXISTS media_type VARCHAR(20);
ALTER TABLE questions ADD COLUMN IF NOT EXISTS year INTEGER;
