"""Add is_answered and LONG_ANSWER

Revision ID: 286d6d83545a
Revises: 4337d68bb9ea
Create Date: 2026-03-26 23:39:54.260475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286d6d83545a'
down_revision: Union[str, Sequence[str], None] = '4337d68bb9ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('is_answered', sa.Boolean(), nullable=True))
    op.execute("ALTER TYPE questiontype ADD VALUE IF NOT EXISTS 'LONG_ANSWER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'is_answered')
    # ### end Alembic commands ###
