"""add year to file artifacts

Revision ID: 4337d68bb9ea
Revises: 433e0e835ae9
Create Date: 2026-03-22 21:57:24.965382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4337d68bb9ea'
down_revision: Union[str, Sequence[str], None] = '433e0e835ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_artifacts', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_artifacts', 'year')
    # ### end Alembic commands ###
