"""update_question_model_for_bank

Revision ID: 433e0e835ae9
Revises: a75283860c91
Create Date: 2026-03-17 23:27:44.539361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433e0e835ae9'
down_revision: Union[str, Sequence[str], None] = 'a75283860c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('file_artifact_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('is_bank_question', sa.Boolean(), nullable=True))
    op.add_column('questions', sa.Column('grade_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'file_artifacts', ['file_artifact_id'], ['id'])
    op.create_foreign_key(None, 'questions', 'grades', ['grade_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'grade_id')
    op.drop_column('questions', 'is_bank_question')
    op.drop_column('questions', 'file_artifact_id')
    # ### end Alembic commands ###
