"""change assignment title to text

Revision ID: 5278befb59bb
Revises: ac32700886aa
Create Date: 2026-02-24 10:33:28.590190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5278befb59bb'
down_revision: Union[str, Sequence[str], None] = 'ac32700886aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
