"""Add is_question_bank to FileArtifact

Revision ID: a75283860c91
Revises: f3a1b2c4d5e6
Create Date: 2026-03-16 23:37:56.694751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75283860c91'
down_revision: Union[str, Sequence[str], None] = 'f3a1b2c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Populate existing NULLs before applying NOT NULL constraints
    op.execute("UPDATE assignments SET title = 'Untitled' WHERE title IS NULL")
    op.alter_column('assignments', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('file_artifacts', sa.Column('is_question_bank', sa.Boolean(), nullable=True))
    op.add_column('questions', sa.Column('year', sa.Integer(), nullable=True))
    
    op.execute("UPDATE subjects SET active = true WHERE active IS NULL")
    op.alter_column('subjects', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subjects', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('questions', 'year')
    op.drop_column('file_artifacts', 'is_question_bank')
    op.alter_column('assignments', 'title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
