"""Sync models

Revision ID: ac32700886aa
Revises: e4b2f7c9a1d0
Create Date: 2026-02-23 00:37:38.915717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac32700886aa'
down_revision: Union[str, Sequence[str], None] = 'e4b2f7c9a1d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_table('curriculums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculums_id'), 'curriculums', ['id'], unique=False)
    op.create_table('school_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_types_id'), 'school_types', ['id'], unique=False)
    op.create_table('grade_subjects',
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('grade_id', 'subject_id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('question_type', sa.Enum('MULTIPLE_CHOICE', 'TRUE_FALSE', 'SHORT_ANSWER', name='questiontype'), nullable=True),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('parent_question_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['parent_question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_options_id'), 'question_options', ['id'], unique=False)
    op.create_table('student_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['question_options.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_answers_id'), 'student_answers', ['id'], unique=False)
    op.add_column('assignments', sa.Column('exam_type', sa.String(length=50), nullable=True))
    op.add_column('assignments', sa.Column('question_count', sa.Integer(), nullable=True))
    op.add_column('assignments', sa.Column('difficulty_level', sa.String(length=20), nullable=True))
    op.add_column('assignments', sa.Column('question_type', sa.String(length=50), nullable=True))
    op.add_column('file_artifacts', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('file_artifacts', sa.Column('stored_filename', sa.String(length=255), nullable=True))
    op.add_column('file_artifacts', sa.Column('relative_path', sa.String(length=500), nullable=True))
    op.add_column('file_artifacts', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('file_artifacts', sa.Column('file_extension', sa.String(length=20), nullable=True))
    op.add_column('file_artifacts', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('file_artifacts', sa.Column('file_status', sa.String(length=50), nullable=True))
    op.add_column('file_artifacts', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('file_artifacts', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    op.add_column('file_artifacts', sa.Column('file_metadata', sa.Text(), nullable=True))
    op.add_column('file_artifacts', sa.Column('school_id', sa.Integer(), nullable=True))
    op.add_column('file_artifacts', sa.Column('grade_id', sa.Integer(), nullable=True))
    op.add_column('file_artifacts', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'file_artifacts', 'schools', ['school_id'], ['id'])
    op.create_foreign_key(None, 'file_artifacts', 'grades', ['grade_id'], ['id'])
    op.create_foreign_key(None, 'file_artifacts', 'subjects', ['subject_id'], ['id'])
    op.drop_column('file_artifacts', 'filename')
    op.drop_column('file_artifacts', 'file_path')
    op.drop_column('file_artifacts', 'file_type')
    op.add_column('schools', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('curriculum_id', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('school_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'schools', 'school_types', ['school_type_id'], ['id'])
    op.create_foreign_key(None, 'schools', 'countries', ['country_id'], ['id'])
    op.create_foreign_key(None, 'schools', 'curriculums', ['curriculum_id'], ['id'])
    op.add_column('students', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'])
    op.add_column('subjects', sa.Column('code', sa.String(length=20), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('subjects', 'code')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'user_id')
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_column('schools', 'school_type_id')
    op.drop_column('schools', 'curriculum_id')
    op.drop_column('schools', 'country_id')
    op.add_column('file_artifacts', sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('file_artifacts', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('file_artifacts', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'file_artifacts', type_='foreignkey')
    op.drop_constraint(None, 'file_artifacts', type_='foreignkey')
    op.drop_constraint(None, 'file_artifacts', type_='foreignkey')
    op.drop_column('file_artifacts', 'subject_id')
    op.drop_column('file_artifacts', 'grade_id')
    op.drop_column('file_artifacts', 'school_id')
    op.drop_column('file_artifacts', 'file_metadata')
    op.drop_column('file_artifacts', 'uploaded_at')
    op.drop_column('file_artifacts', 'description')
    op.drop_column('file_artifacts', 'file_status')
    op.drop_column('file_artifacts', 'file_size')
    op.drop_column('file_artifacts', 'file_extension')
    op.drop_column('file_artifacts', 'mime_type')
    op.drop_column('file_artifacts', 'relative_path')
    op.drop_column('file_artifacts', 'stored_filename')
    op.drop_column('file_artifacts', 'original_filename')
    op.drop_column('assignments', 'question_type')
    op.drop_column('assignments', 'difficulty_level')
    op.drop_column('assignments', 'question_count')
    op.drop_column('assignments', 'exam_type')
    op.drop_index(op.f('ix_student_answers_id'), table_name='student_answers')
    op.drop_table('student_answers')
    op.drop_index(op.f('ix_question_options_id'), table_name='question_options')
    op.drop_table('question_options')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('grade_subjects')
    op.drop_index(op.f('ix_school_types_id'), table_name='school_types')
    op.drop_table('school_types')
    op.drop_index(op.f('ix_curriculums_id'), table_name='curriculums')
    op.drop_table('curriculums')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
