"""Add question paper models

Revision ID: ae682c467dad
Revises: f3a1b2c4d5e6
Create Date: 2026-03-18 12:46:38.547551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae682c467dad'
down_revision: Union[str, Sequence[str], None] = 'f3a1b2c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_types_id'), 'exam_types', ['id'], unique=False)
    op.create_table('question_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('board', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('exam_type', sa.String(length=100), nullable=True),
    sa.Column('academic_year', sa.String(length=50), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('set_number', sa.String(length=50), nullable=True),
    sa.Column('sections_config', sa.Text(), nullable=True),
    sa.Column('general_instructions', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_papers_id'), 'question_papers', ['id'], unique=False)
    op.create_table('paper_question_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('section_name', sa.String(length=100), nullable=False),
    sa.Column('order_in_section', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['question_papers.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_question_mappings_id'), 'paper_question_mappings', ['id'], unique=False)
    op.drop_constraint(op.f('fk_assignments_school'), 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'created_at')
    op.drop_column('assignments', 'school_id')
    op.add_column('questions', sa.Column('source_year', sa.String(length=20), nullable=True))
    op.add_column('questions', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.add_column('questions', sa.Column('bloom_level', sa.String(length=50), nullable=True))
    op.add_column('questions', sa.Column('chapter_name', sa.String(length=255), nullable=True))
    op.add_column('questions', sa.Column('passage', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('sub_questions', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('answer_key', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('correct_answer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'correct_answer')
    op.drop_column('questions', 'answer_key')
    op.drop_column('questions', 'sub_questions')
    op.drop_column('questions', 'passage')
    op.drop_column('questions', 'chapter_name')
    op.drop_column('questions', 'bloom_level')
    op.drop_column('questions', 'source_type')
    op.drop_column('questions', 'source_year')
    op.add_column('assignments', sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assignments', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_assignments_school'), 'assignments', 'schools', ['school_id'], ['id'])
    op.drop_index(op.f('ix_paper_question_mappings_id'), table_name='paper_question_mappings')
    op.drop_table('paper_question_mappings')
    op.drop_index(op.f('ix_question_papers_id'), table_name='question_papers')
    op.drop_table('question_papers')
    op.drop_index(op.f('ix_exam_types_id'), table_name='exam_types')
    op.drop_table('exam_types')
    # ### end Alembic commands ###
