"""Add generation_type

Revision ID: d0755676692a
Revises: b1c2d3e4f5a6
Create Date: 2026-03-25 10:57:39.562917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0755676692a'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('generation_type', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('fk_question_papers_template_id'), 'question_papers', type_='foreignkey')
    op.create_foreign_key(None, 'question_papers', 'paper_templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_papers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_question_papers_template_id'), 'question_papers', 'paper_templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.drop_column('assignments', 'generation_type')
    # ### end Alembic commands ###
