"""add_status_to_question_paper

Revision ID: e55806033795
Revises: d0755676692a
Create Date: 2026-03-26 18:48:50.407859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55806033795'
down_revision: Union[str, Sequence[str], None] = 'd0755676692a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_papers', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_papers', 'status')
    # ### end Alembic commands ###
