"""add grade_id to assignments v2

Revision ID: 49db749eab61
Revises: e4b2f7c9a1d0
Create Date: 2026-02-25 21:36:24.181432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49db749eab61'
down_revision: Union[str, Sequence[str], None] = 'e4b2f7c9a1d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Standard add column is safe in SQLite if nullable or having default
    op.add_column('assignments', sa.Column('grade_id', sa.Integer(), nullable=True))
    
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('title',
                   existing_type=sa.VARCHAR(length=100),
                   type_=sa.String(length=200),
                   existing_nullable=True)
        batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=10),
                   type_=sa.Enum('DRAFT', 'PUBLISHED', name='assignmentstatus'),
                   existing_nullable=True)
        batch_op.create_foreign_key('fk_assignments_grade_id', 'grades', ['grade_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=False)
        batch_op.drop_index('ix_users_username')
        batch_op.create_index('ix_users_username', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username')
        batch_op.create_index('ix_users_username', ['username'], unique=True)
        batch_op.alter_column('hashed_password',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True)

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assignments_grade_id', type_='foreignkey')
        batch_op.alter_column('status',
                   existing_type=sa.Enum('DRAFT', 'PUBLISHED', name='assignmentstatus'),
                   type_=sa.VARCHAR(length=10),
                   existing_nullable=True)
        batch_op.alter_column('title',
                   existing_type=sa.String(length=200),
                   type_=sa.VARCHAR(length=100),
                   existing_nullable=True)
        batch_op.drop_column('grade_id')
    # ### end Alembic commands ###
